/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-09-24 04:11:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_005fHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/HP/OneDrive/Desktop/MBS%20new/Movie%20browsing%20system/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/Sriflix/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1726746182834L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Guest_and_srcs/Styles/bootstrap.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.0/font/bootstrap-icons.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Guest_and_srcs/Styles/admin1_home.css\">\r\n");
      out.write("    <title>Sriflix</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navigation bar -->\r\n");
      out.write("    <nav>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"logo\">Sriflix</div> \r\n");
      out.write("\r\n");
      out.write("            <div class=\"navlinks\">                               \r\n");
      out.write("                <a class=\"active\" href=\"AdminmovieShowcontroller\">Home</a>\r\n");
      out.write("                <a href=\"#\">News</a>\r\n");
      out.write("                <a  href=\"#\">Actors</a>\r\n");
      out.write("                <a href=\"#\">Contact Us</a>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"buttons\">\r\n");
      out.write("                    <a href=\"dashboard.html\">Dashboard</a>\r\n");
      out.write("                    <a href=\"#\">Profile</a>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- End navigation bar -->\r\n");
      out.write("\r\n");
      out.write("<!-- carousel -->\r\n");
      out.write("<div id=\"movieCarousel\" class=\"carousel slide \" data-bs-ride=\"carousel\"data-bs-interval=\"3000\" >\r\n");
      out.write("    <div class=\"carousel-inner\">\r\n");
      out.write("        <div class=\"carousel-item active\" style=\"background-image: url(' Guest_and_srcs/Images/Image1.jpg');border-radius: 20px;\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Pathaan</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ex earum cumque quaerat eveniet officia inventore eum nulla, quae ducimus deserunt. Consectetur nulla libero totam eos accusantium enim at temporibus recusandae!</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url(' Guest_and_srcs/Images/Image2.jpg');border-radius: 20px\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Brave</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias porro odit voluptas debitis deleniti! Tempora ipsa laudantium at quae numquam accusamus perspiciatis fuga sit deleniti. Numquam non exercitationem dolores facilis.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url(' Guest_and_srcs/Images/Image3.jpg');border-radius: 20px\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>London Has Fallen</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae qui nobis aliquam veniam? Minima, omnis rem placeat magni eius quam, illum quia unde inventore saepe ullam culpa beatae veritatis quod.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url(' Guest_and_srcs/Images/Image4.jpg');border-radius: 20px\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>The Lego Movie</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus qui, reprehenderit optio distinctio, sapiente voluptatem fugiat quasi facere, dolorum consectetur explicabo nisi dicta facilis neque consequatur voluptas aspernatur. Quos, labore.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url(' Guest_and_srcs/Images/Image5.jpg');border-radius: 20px\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Avatar</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe ipsam eligendi labore fuga nulla laboriosam soluta ullam qui illum animi repellendus odit veritatis voluptas, eaque et! Sit accusamus porro harum!</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"carousel-item\" style=\"background-image: url(' Guest_and_srcs/Images/Image6.jpg');border-radius: 20px\">\r\n");
      out.write("            <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                <h5>Oppenhiemer</h5>\r\n");
      out.write("                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe ipsam eligendi labore fuga nulla laboriosam soluta ullam qui illum animi repellendus odit veritatis voluptas, eaque et! Sit accusamus porro harum!</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#movieCarousel\" data-bs-slide=\"prev\">\r\n");
      out.write("        <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#movieCarousel\" data-bs-slide=\"next\">\r\n");
      out.write("        <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("        <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("    </button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- end of carousel -->\r\n");
      out.write("\r\n");
      out.write("<!-- movie cards -->\r\n");
      out.write("<h4 style=\"color: rgb(130, 128, 128);margin-top: 50px;margin-left: 45px;margin-bottom: 0;\">Top Movies</h4>\r\n");
      out.write("<div class=\"tcontainer mt-5\">\r\n");
      out.write("    \r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("        <div class=\"card movie-card\">\r\n");
      out.write("            <img src=\"add_sign.jpg\" class=\"card-img-top\" alt=\"Movie Poster 1\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h5 class=\"card-title\">Add Movie</h5>\r\n");
      out.write("                <p class=\"card-text\">Add movie</p>\r\n");
      out.write("                \r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("                        <i class=\"bi bi-plus\"></i> Add Movie\r\n");
      out.write("                    </button>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  		<div class=\"modal-dialog\">\r\n");
      out.write("    		<div class=\"modal-content\">\r\n");
      out.write("      			<div class=\"modal-header\">\r\n");
      out.write("        			<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Insert A New Movie</h1>\r\n");
      out.write("        			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      			</div>\r\n");
      out.write("      			<div class=\"modal-body\">\r\n");
      out.write("        		<form action=\"imageuploadServelet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("          		<!-- Movie Name Input -->\r\n");
      out.write("         			 <div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieName\" class=\"form-label\">Movie Name</label>\r\n");
      out.write("            			<input type=\"text\" class=\"form-control\" id=\"movieName\" name=\"movieName\" placeholder=\"Enter Movie Name\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Short Description Input -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"shortDescription\" class=\"form-label\">Short Description</label>\r\n");
      out.write("            			<input type=\"text\" class=\"form-control\" id=\"shortDescription\" name=\"shortDescription\" placeholder=\"Enter Short Description\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Long Description Input -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"longDescription\" class=\"form-label\">Long Description</label>\r\n");
      out.write("            			<textarea class=\"form-control\" id=\"longDescription\" name=\"longDescription\" rows=\"3\" placeholder=\"Enter Long Description\" required></textarea>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Upload Movie Image -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieImage\" class=\"form-label\">Upload Movie Image</label>\r\n");
      out.write("            			<input type=\"file\" class=\"form-control\" id=\"movieImage\" name=\"movieImage\" accept=\"image/*\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Upload Movie File -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieFile\" class=\"form-label\">Upload Movie File</label>\r\n");
      out.write("            			<input type=\"file\" class=\"form-control\" id=\"movieFile\" name=\"movieFile\" accept=\"video/*\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("          			<div class=\"modal-footer\">\r\n");
      out.write("        			<button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("        			<button type=\"submit\" class=\"btn btn-primary\">Save Movie</button>\r\n");
      out.write("      			</div>\r\n");
      out.write("        		</form>\r\n");
      out.write("     	 		</div>\r\n");
      out.write("      			\r\n");
      out.write("    		</div>\r\n");
      out.write("  		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(" <!-- end of movie cards -->\r\n");
      out.write("\r\n");
      out.write("<!-- poster -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"jumbotron\">\r\n");
      out.write("        <div class=\"overlay\">\r\n");
      out.write("            <div class=\"txt\">\r\n");
      out.write("                \r\n");
      out.write("                 <h1 class=\"display-4\" >Welcome Admin! </h1>\r\n");
      out.write("                 <p class=\"lead\">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>\r\n");
      out.write("                 <hr class=\"my-4\">\r\n");
      out.write("                 <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- end of poster -->\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"bg-dark text-white py-4\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h5 style=\"text-align: center;\">About Us</h5>\r\n");
      out.write("        <p>Your movie browsing system is a platform to explore and enjoy a wide range of movies and TV series. Discover your next favorite movie with us.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"text-center col-md-4\">\r\n");
      out.write("        <h5 >Quick Links</h5>\r\n");
      out.write("        <ul  class=\"list-unstyled\">\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Home</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Browse Movies</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Privacy Policy</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-md-3\">\r\n");
      out.write("        <h5>Follow Us On</h5>\r\n");
      out.write("        <a href=\"https://www.facebook.com/\" class=\"text-white me-2\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("        <a href=\"https://x.com/?lang=en&mx=2\" class=\"text-white me-2\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("        <a href=\"https://www.instagram.com/\" class=\"text-white me-2\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("        <a href=\"https://www.youtube.com\" class=\"text-white\"><i class=\"bi bi-youtube\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"text-center pt-3\">\r\n");
      out.write("      <p>&copy; 2024 OOP Movie Browsing System. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</footer> \r\n");
      out.write("<!-- end footer -->\r\n");
      out.write("<script src=\" Guest_and_srcs/JS/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /admin_Home.jsp(103,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("Movies");
      // /admin_Home.jsp(103,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/admin_Home.jsp(103,0) '${movieDetails}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${movieDetails}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	\r\n");
            out.write("    <!-- Movie Card -->\r\n");
            out.write("    <div class=\"col-lg-3 col-md-6\">\r\n");
            out.write("        <div class=\"card movie-card\">\r\n");
            out.write("            <img src=\"UploadedImages/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieimgPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"card-img-top\" alt=\"Movie Poster\">\r\n");
            out.write("            <div class=\"card-body\">\r\n");
            out.write("                <h5 class=\"card-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                <p class=\"card-text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieshortdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                <button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#Updateform");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                    <i class=\"bi bi-pen\"></i> Edit Movie Details\r\n");
            out.write("                </button>\r\n");
            out.write("                <button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#deleteform");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                    <i class=\"bi bi-trash\"></i> Delete Movie \r\n");
            out.write("                </button>\r\n");
            out.write("                	<form action=\"MoviewatchServelet\" method=\"post\">\r\n");
            out.write("                        \r\n");
            out.write("                        <input type=\"hidden\" name=\"movieId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                        <button class=\"btn btn-primary\">\r\n");
            out.write("                        <i class=\"bi bi-play-circle\"></i> Watch Movie\r\n");
            out.write("                        </button>\r\n");
            out.write("                    </form>\r\n");
            out.write("                \r\n");
            out.write("                \r\n");
            out.write("           	    \r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("    </div>\r\n");
            out.write("\r\n");
            out.write("    <!-- Update form -->\r\n");
            out.write("    <div class=\"modal fade\" id=\"Updateform");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" tabindex=\"-1\" aria-labelledby=\"UpdateformLabel");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" aria-hidden=\"true\">\r\n");
            out.write("        <div class=\"modal-dialog\">\r\n");
            out.write("            <div class=\"modal-content\">\r\n");
            out.write("                <div class=\"modal-header\">\r\n");
            out.write("                    <h1 class=\"modal-title fs-5\" id=\"UpdateformLabel");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Update Movie</h1>\r\n");
            out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("                </div>\r\n");
            out.write("                <div class=\"modal-body\">\r\n");
            out.write("                    <form action=\"MovieUpdateServelet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
            out.write("                        <input type=\"hidden\" name=\"movieId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("                        <div class=\"mb-3\">\r\n");
            out.write("                            <label for=\"movieName\" class=\"form-label\">Movie Name</label>\r\n");
            out.write("                            <input type=\"text\" class=\"form-control\" id=\"movieName\" name=\"movieName\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" >\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"mb-3\">\r\n");
            out.write("                            <label for=\"shortDescription\" class=\"form-label\">Short Description</label>\r\n");
            out.write("                            <textarea class=\"form-control\" id=\"shortDescription\" name=\"shortDescription\" rows=\"3\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieshortdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</textarea>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"mb-3\">\r\n");
            out.write("                            <label for=\"longDescription\" class=\"form-label\">Long Description</label>\r\n");
            out.write("                            <textarea class=\"form-control\" id=\"longDescription\" name=\"longDescription\" rows=\"3\" >");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movielongdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</textarea>\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"mb-3\">\r\n");
            out.write("                            <label for=\"movieImage\" class=\"form-label\">Upload Movie Image</label>\r\n");
            out.write("                            <input type=\"file\" class=\"form-control\" id=\"movieImage\" name=\"movieImage\"accept=\"image/*\">\r\n");
            out.write("                        </div>\r\n");
            out.write("                        <div class=\"mb-3\">\r\n");
            out.write("            				<label for=\"movieFile\" class=\"form-label\">Upload Movie File</label>\r\n");
            out.write("            				<input type=\"file\" class=\"form-control\" id=\"movieFile\" name=\"movieFile\"accept=\"video/*\" >\r\n");
            out.write("          				</div>\r\n");
            out.write("                        <div class=\"modal-footer\">\r\n");
            out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
            out.write("                            <button type=\"submit\" class=\"btn btn-primary\">Save Movie</button>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </form>\r\n");
            out.write("                </div>\r\n");
            out.write("            </div>\r\n");
            out.write("        </div>\r\n");
            out.write("    </div>\r\n");
            out.write("    <!-- Delete form -->\r\n");
            out.write("    <div class=\"modal\" tabindex=\"-1\"id=\"deleteform");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("  <div class=\"modal-dialog\">\r\n");
            out.write("    <div class=\"modal-content\">\r\n");
            out.write("      <div class=\"modal-header\">\r\n");
            out.write("        <h5 class=\"modal-title\">Alert!</h5>\r\n");
            out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("      </div>\r\n");
            out.write("      <div class=\"modal-body\">\r\n");
            out.write("      <form action=\"MovieDeleteServelet\" method=\"post\">\r\n");
            out.write("      <input type=\"hidden\" name=\"movieId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" />\r\n");
            out.write("        <p>Are You sure You want to delete ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" ! </p>\r\n");
            out.write("      \r\n");
            out.write("     \r\n");
            out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">No</button>\r\n");
            out.write("        <button type=\"submit\" class=\"btn btn-primary\">Yes</button>\r\n");
            out.write("      \r\n");
            out.write("      \r\n");
            out.write("      </form>\r\n");
            out.write("       \r\n");
            out.write("      </div>\r\n");
            out.write("      \r\n");
            out.write("    </div>\r\n");
            out.write("  </div>\r\n");
            out.write("</div>\r\n");
            out.write("    \r\n");
            out.write("    \r\n");
            out.write("	\r\n");
            out.write("	\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
