/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-09-21 18:39:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Admin_005fMovies_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"Guest_and_srcs/Styles/bootstrap.min.css\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"Guest_and_srcs/Styles/admin1_home.css\">\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("        \r\n");
      out.write("        <title>Sriflix</title>\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- navigation bar -->\r\n");
      out.write("    <nav>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"logo\">Sriflix</div> \r\n");
      out.write("\r\n");
      out.write("            <div class=\"navlinks\">                               \r\n");
      out.write("                <a  href=\"AdminmovieShowcontroller\">Home</a>\r\n");
      out.write("                <a class=\"active\" href=\"Admin_Movies.html\">Movies</a>\r\n");
      out.write("                <a  href=\"actors.html\">Actors</a>\r\n");
      out.write("                <a href=\"#\">Contact Us</a>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"buttons\">\r\n");
      out.write("                <a href=\"dashboard.html\">Dashboard</a>\r\n");
      out.write("                <a href=\"#\">Profile</a>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- End navigation bar -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- movie cards -->\r\n");
      out.write("<h4 style=\"color: rgb(130, 128, 128);margin-top: 50px;margin-left: 45px;margin-bottom: 0;\">Top Movies</h4>\r\n");
      out.write("<div class=\"tcontainer mt-5\">\r\n");
      out.write("    \r\n");
      out.write("<c:forEach var=\"Movies\" items=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${movieDetails}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    <!-- Movie Card -->\r\n");
      out.write("    <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("        <div class=\"card movie-card\">\r\n");
      out.write("            <img src=\"UploadedImages/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieimgPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"card-img-top\" alt=\"Movie Poster\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h5 class=\"card-title\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("                <p class=\"card-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieshortdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#Updateform");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <i class=\"bi bi-pen\"></i> Edit Movie Details\r\n");
      out.write("                </button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#deleteform");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <i class=\"bi bi-trash\"></i> Delete Movie \r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Update form -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"Updateform");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" tabindex=\"-1\" aria-labelledby=\"UpdateformLabel");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h1 class=\"modal-title fs-5\" id=\"UpdateformLabel");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Update Movie</h1>\r\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    <form action=\"MovieUpdateServelet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"movieId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"movieName\" class=\"form-label\">Movie Name</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"movieName\" name=\"movieName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" >\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"shortDescription\" class=\"form-label\">Short Description</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"shortDescription\" name=\"shortDescription\" rows=\"3\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieshortdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"longDescription\" class=\"form-label\">Long Description</label>\r\n");
      out.write("                            <textarea class=\"form-control\" id=\"longDescription\" name=\"longDescription\" rows=\"3\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movielongdes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label for=\"movieImage\" class=\"form-label\">Upload Movie Image</label>\r\n");
      out.write("                            <input type=\"file\" class=\"form-control\" id=\"movieImage\" name=\"movieImage\"accept=\"image/*\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("            				<label for=\"movieFile\" class=\"form-label\">Upload Movie File</label>\r\n");
      out.write("            				<input type=\"file\" class=\"form-control\" id=\"movieFile\" name=\"movieFile\"accept=\"video/*\" >\r\n");
      out.write("          				</div>\r\n");
      out.write("                        <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\">Save Movie</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Delete form -->\r\n");
      out.write("    <div class=\"modal\" tabindex=\"-1\"id=\"deleteform");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\">Alert!</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      <form action=\"MovieDeleteServelet\" method=\"post\">\r\n");
      out.write("      <input type=\"hidden\" name=\"movieId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.movieid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("        <p>Are You sure You want to delete ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Movies.moviename}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ! </p>\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">No</button>\r\n");
      out.write("        <button type=\"submit\" class=\"btn btn-primary\">Yes</button>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      </form>\r\n");
      out.write("       \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</c:forEach>\r\n");
      out.write("       \r\n");
      out.write("       <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("        <div class=\"card movie-card\">\r\n");
      out.write("            <img src=\"add_sign.jpg\" class=\"card-img-top\" alt=\"Movie Poster 1\">\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("                <h5 class=\"card-title\">Add Movie</h5>\r\n");
      out.write("                <p class=\"card-text\">Add movie</p>\r\n");
      out.write("                \r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("                        <i class=\"bi bi-plus\"></i> Add Movie\r\n");
      out.write("                    </button>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  		<div class=\"modal-dialog\">\r\n");
      out.write("    		<div class=\"modal-content\">\r\n");
      out.write("      			<div class=\"modal-header\">\r\n");
      out.write("        			<h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Insert A New Movie</h1>\r\n");
      out.write("        			<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      			</div>\r\n");
      out.write("      			<div class=\"modal-body\">\r\n");
      out.write("        		<form action=\"imageuploadServelet\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("          		<!-- Movie Name Input -->\r\n");
      out.write("         			 <div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieName\" class=\"form-label\">Movie Name</label>\r\n");
      out.write("            			<input type=\"text\" class=\"form-control\" id=\"movieName\" name=\"movieName\" placeholder=\"Enter Movie Name\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Short Description Input -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"shortDescription\" class=\"form-label\">Short Description</label>\r\n");
      out.write("            			<input type=\"text\" class=\"form-control\" id=\"shortDescription\" name=\"shortDescription\" placeholder=\"Enter Short Description\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Long Description Input -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"longDescription\" class=\"form-label\">Long Description</label>\r\n");
      out.write("            			<textarea class=\"form-control\" id=\"longDescription\" name=\"longDescription\" rows=\"3\" placeholder=\"Enter Long Description\" required></textarea>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Upload Movie Image -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieImage\" class=\"form-label\">Upload Movie Image</label>\r\n");
      out.write("            			<input type=\"file\" class=\"form-control\" id=\"movieImage\" name=\"movieImage\" accept=\"image/*\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("\r\n");
      out.write("          		<!-- Upload Movie File -->\r\n");
      out.write("          			<div class=\"mb-3\">\r\n");
      out.write("            			<label for=\"movieFile\" class=\"form-label\">Upload Movie File</label>\r\n");
      out.write("            			<input type=\"file\" class=\"form-control\" id=\"movieFile\" name=\"movieFile\" accept=\"video/*\" required>\r\n");
      out.write("          			</div>\r\n");
      out.write("          			<div class=\"modal-footer\">\r\n");
      out.write("        			<button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("        			<button type=\"submit\" class=\"btn btn-primary\">Save Movie</button>\r\n");
      out.write("      			</div>\r\n");
      out.write("        		</form>\r\n");
      out.write("     	 		</div>\r\n");
      out.write("      			\r\n");
      out.write("    		</div>\r\n");
      out.write("  		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write(" <!-- end of movie cards -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<footer class=\"bg-dark text-white py-4\">\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-md-4\">\r\n");
      out.write("        <h5 style=\"text-align: center;\">About Us</h5>\r\n");
      out.write("        <p>Your movie browsing system is a platform to explore and enjoy a wide range of movies and TV series. Discover your next favorite movie with us.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"text-center col-md-4\">\r\n");
      out.write("        <h5 >Quick Links</h5>\r\n");
      out.write("        <ul  class=\"list-unstyled\">\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Home</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Browse Movies</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"#\" class=\"text-white\">Privacy Policy</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"col-md-3\">\r\n");
      out.write("        <h5>Follow Us On</h5>\r\n");
      out.write("        <a href=\"https://www.facebook.com/\" class=\"text-white me-2\"><i class=\"bi bi-facebook\"></i></a>\r\n");
      out.write("        <a href=\"https://x.com/?lang=en&mx=2\" class=\"text-white me-2\"><i class=\"bi bi-twitter\"></i></a>\r\n");
      out.write("        <a href=\"https://www.instagram.com/\" class=\"text-white me-2\"><i class=\"bi bi-instagram\"></i></a>\r\n");
      out.write("        <a href=\"https://www.youtube.com\" class=\"text-white\"><i class=\"bi bi-youtube\"></i></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"text-center pt-3\">\r\n");
      out.write("      <p>&copy; 2024 OOP Movie Browsing System. All rights reserved.</p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</footer> \r\n");
      out.write("<!-- end footer -->\r\n");
      out.write("<script src=\" Guest_and_srcs/JS/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
